apiVersion: apps/v1
kind: Deployment
metadata:
  name: tito
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tito
  template:
    metadata:
      labels:
        app: tito
    spec:
      containers:
      - name: tito
        image: adabalap/tito:a297600a
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports: 
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: tito-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tito
  ports:
  - port: 5000
  externalIPs:
    - 192.168.1.110

